
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: on push
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
#     - name: Install pipenv
#       run: |
#         cd model && python -m pip install --upgrade pipenv wheel
#     - id: cache-pipenv
#       uses: actions/cache@v1
#       with:
#         path: ~/.local/share/virtualenvs
#         key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
    - name: Build
      run: |
        cd model && 
        pip install -e .
    - name: Running pytest
      run: |
        cd model && pytest
